# Unit Test reusable workflow ab
name: Unit Test

on:
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  # Single deploy job since we're just deploying abcdef

  execut_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: show branch
        run: echo steps.extract_branch.outputs.branch
      - name: Execute
        run: exit 1
